---
swagger: "2.0"
info:
  description: "Предоставляет необходимые данные для мониторинга актуальной информации по конвейеру на экране телевизора"
  version: "1.0"
  title: "Визуализация конвейера API"
host: "localhost"
basePath: "/viz"
tags:
- name: "conveyer"
  description: "Очередь конвейера"
- name: "nzp"
  description: "Незавершенное производство"
- name: "sgp"
  description: "Склад готовой продукции"
- name: "beats"
  description: "Такт конвейера"
schemes:
- "http"
paths:
  /conveyer:
    get:
      tags:
      - "conveyer"
      summary: "Информация по постам"
      description: "Значения по умолчанию: from = 2, to = 28."
      operationId: "conveyer"
      produces:
      - "application/json"
      parameters:
      - name: "from"
        in: "query"
        description: "Номер начального поста"
        required: false
        type: "integer"
      - name: "to"
        in: "query"
        description: "Номер конечного поста"
        required: false
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/conveyer"
        400:
          description: "Invalid status value"
  /nzp:
    get:
      tags:
      - "nzp"
      summary: "Количество в разрезе моделей"
      description: ""
      operationId: "nzp"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/nzp"
        400:
          description: "Invalid status value"
      deprecated: false
  /sgp:
    get:
      tags:
      - "sgp"
      summary: "Finds Pets by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "sgp"
      produces:
      - "application/json"
      responses:
        400:
          description: "Invalid status value"
      deprecated: true
  /beats:
    get:
      tags:
      - "beats"
      summary: "Finds Pets by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "beats"
      produces:
      - "application/json"
      responses:
        400:
          description: "Invalid status value"
      deprecated: true
definitions:
  conveyer:
    type: "object"
    properties:
      errors:
        type: "string"
        example: ""
      posts:
        type: "array"
        xml:
          wrapped: true
        items:
          xml:
            name: "posts"
          $ref: "#/definitions/posts"
    xml:
      name: "conveyer"
  nzp:
    type: "object"
    properties:
      total:
        type: "integer"
        example: "2"
      errors:
        type: "string"
        example: ""
      models:
        type: "array"
        xml:
          wrapped: true
        items:
          xml:
            name: "models"
          $ref: "#/definitions/models"
      tsm:
        type: "array"
        xml:
          wrapped: true
        items:
          xml:
            name: "tsm"
          $ref: "#/definitions/tsm"
    xml:
      name: "nzp"
  models:
    type: "object"
    properties:
      model:
        type: "string"
        example: "RAV4"
      count:
        type: "integer"
        example: "2"
    xml:
      name: "models"
  tsm:
    type: "object"
    properties:
      period:
        type: "string"
        example: "за день"
      count:
        type: "integer"
        example: 12
    xml:
      name: "tsm"
  posts:
    type: "object"
    properties:
      post:
        type: "integer"
        example: "2"
      model:
        type: "string"
        example: "RAV4"
      vin:
        type: "string"
        example: "VIN 2096415"
      color:
        type: "string"
        example: "СЕРЫЙ"
      help:
        type: "boolean"
      delay:
        type: "boolean"
      expired:
        type: "integer"
        example: "1"
    xml:
      name: "posts"